spring:
  security:
    pat:
      pats:
      - principal: user1
        token: pat1111
        scopes:
        - read
        issued-at: 1735603200000    # Tuesday, 31 December 2024 00:00:00
        expires-at: 1767139200000   # Wednesday, 31 December 2025 00:00:00
        not-before: 1735603200000   # Tuesday, 31 December 2024 00:00:00
      - principal: user2
        token: pat2222
        scopes:
        - read
        - write
        issued-at: 1735603200000    # Tuesday, 31 December 2024 00:00:00
        expires-at: 1767139200000   # Wednesday, 31 December 2025 00:00:00
        not-before: 1735603200000   # Tuesday, 31 December 2024 00:00:00
